# Generated by Django 3.2.6 on 2024-08-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettermembers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
