# Generated by Django 3.2.6 on 2023-09-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='facebook_link',
            field=models.CharField(default='https://www.facebook.com', max_length=555),
        ),
        migrations.AddField(
            model_name='account',
            name='image_link',
            field=models.CharField(default='https://preview.redd.it/h5gnz1ji36o61.png?width=225&format=png&auto=webp&s=84379f8d3bbe593a2e863c438cd03e84c8a474fa', max_length=555),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(1, 'President'), (2, 'Internal Vice President'), (3, 'External Vice President'), (4, 'Treasurer'), (5, 'Secretary'), (6, 'Assistant Secretary'), (7, 'Auditor'), (8, 'Outreach Program Director'), (9, 'Event Coordinator'), (10, 'Public Information Officer'), (11, 'Digital Officer'), (12, 'Representative'), (13, 'Member')], default=0),
            preserve_default=False,
        ),
    ]
