# Generated by Django 3.2.6 on 2023-09-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20230926_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['role']},
        ),
    ]
