# Generated by Django 3.2.6 on 2023-10-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
