# Generated by Django 3.2.6 on 2023-10-21 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_announcements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
