# Generated by Django 3.2.6 on 2023-10-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_status',
            field=models.CharField(blank=True, default='Upcoming', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_flyer',
            field=models.FileField(blank=True, null=True, upload_to='Models/static'),
        ),
    ]
