# Generated by Django 4.0.2 on 2023-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_alter_announcements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='content',
            field=models.CharField(max_length=10000),
        ),
    ]
