# Generated by Django 3.2.6 on 2023-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_auto_20231101_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='msg',
            field=models.TextField(max_length=1028),
        ),
    ]
