# Generated by Django 3.2.6 on 2023-10-22 14:00

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_alter_announcements_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='content',
            field=markdownx.models.MarkdownxField(max_length=10000),
        ),
    ]
