# Generated by Django 3.2.6 on 2023-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0008_alter_announcements_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='thumbnail',
            field=models.ImageField(blank=True, default='domini_xode_logo.jpg', null=True, upload_to='static/'),
        ),
    ]
