# Generated by Django 3.2.6 on 2024-08-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0010_alter_announcements_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
    ]
