# Generated by Django 3.2.6 on 2024-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_announcements_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='broadcast_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/domini_xode_logo.jpg', null=True, upload_to='static/'),
        ),
    ]
