# Generated by Django 3.2.6 on 2024-08-23 01:21

import About.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='year_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[(1, 'President'), (2, 'Internal Vice President'), (3, 'External Vice President'), (4, 'Treasurer'), (5, 'Secretary'), (6, 'Assistant Secretary'), (7, 'Auditor'), (8, 'Outreach Program Director'), (9, 'Event Coordinator'), (10, 'Public Information Officer'), (11, 'Digital Officer'), (12, 'Representative'), (13, 'Technical'), (14, 'Documentation'), (15, 'Member')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=About.models.upload_to_officer_images)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='About.year')),
            ],
        ),
    ]
